/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package slack

// Schema for error response from conversations.invite method
type ConversationsInviteErrorSchema1 struct {
	Provided string `json:"provided,omitempty"`

	Errors []ConversationsInviteErrorSchema1Errors `json:"errors,omitempty"`

	Ok bool `json:"ok"`

	Error_ string `json:"error,omitempty"`

	Needed string `json:"needed,omitempty"`
}
