/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package slack

type ObjsUser struct {
	Profile *ObjsUserProfile `json:"profile"`

	Updated float32 `json:"updated"`

	Tz string `json:"tz"`

	Name string `json:"name"`

	Deleted bool `json:"deleted"`

	IsAppUser bool `json:"is_app_user"`

	IsBot bool `json:"is_bot"`

	TzLabel string `json:"tz_label"`

	RealName string `json:"real_name"`

	Locale string `json:"locale,omitempty"`

	TeamId string `json:"team_id"`

	IsAdmin bool `json:"is_admin"`

	IsUltraRestricted bool `json:"is_ultra_restricted"`

	IsOwner bool `json:"is_owner"`

	IsRestricted bool `json:"is_restricted"`

	TzOffset float32 `json:"tz_offset"`

	Has2fa bool `json:"has_2fa,omitempty"`

	Id string `json:"id"`

	Color string `json:"color"`

	IsPrimaryOwner bool `json:"is_primary_owner"`
}
