/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * API version: 1.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package slack

type ObjsUserProfileShort struct {
	FirstName string `json:"first_name"`

	DisplayName string `json:"display_name"`

	Name string `json:"name"`

	Team string `json:"team"`

	RealName string `json:"real_name"`

	AvatarHash string `json:"avatar_hash"`

	IsUltraRestricted bool `json:"is_ultra_restricted"`

	IsRestricted bool `json:"is_restricted"`

	Image72 string `json:"image_72"`
}
